services:
  db:
    image: postgres:16
    container_name: booking_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booking
    ports:
      - "5432:5432"
